setwd("C:/Users/byjs0/OneDrive/바탕 화면/TS")
liverdata = read.csv("indian_liver_patient.csv")
attach(liverdata)
rmfull <- glm(Dataset~Age+Gender+Total_Bilirubin+Direct_Bilirubin+Alkaline_Phosphotase+Alamine_Aminotransferase+Aspartate_Aminotransferase+Total_Protiens+Albumin+Albumin_and_Globulin_Ratio,family="binomial")
rmnull<-glm(Dataset~1,family="binomial")
Reducedrm1 = step(rmnull, scope=list(upper=rmfull), direction="both")
Reducedrm2 = step(rmnull, scope=list(lower = rmnull, upper=rmfull), direction="forward")
Reducedrm3 = step(rmfull, direction="backward")
summary(Reducedrm1)
summary(Reducedrm2)
summary(Reducedrm3)
Reducedrm4<-glm(Dataset~Age+Direct_Bilirubin+Alkaline_Phosphotase+Alamine_Aminotransferase+Albumin+Albumin_and_Globulin_Ratio,family="binomial")
Reducedrm5<-glm(Dataset~Age+Direct_Bilirubin+Alkaline_Phosphotase+Alamine_Aminotransferase+Total_Protiens+Albumin_and_Globulin_Ratio,family="binomial")
Reducedrm6<-glm(Dataset~Age+Direct_Bilirubin+Alkaline_Phosphotase+Alamine_Aminotransferase+Total_Protiens+Albumin,family="binomial")
summary(Reducedrm4)
vif(Reducedrm4)
summary(Reducedrm5)
vif(Reducedrm5)
summary(Reducedrm6)
vif(Reducedrm6)
finalrm=glm(Dataset~Age+Direct_Bilirubin+Alamine_Aminotransferase+Total_Protiens+Albumin,family="binomial")
summary(finalrm)
vif(finalrm)
coef(finalrm)
exp(coef(finalrm))
confint(finalrm)
exp(confint(finalrm))
fitted(finalrm)
res <- residuals(Reducedrm1)
shapiro.test(res)
plot(Reducedrm1)
mydata = data.frame(25,0.3,17,6.7,4.7)
predict(finalrm, liverdata[c(584),], type="response")
